### ISSUE TITLE
Hierarchy Bookmarks do not work on Unity 2020.2

### ISSUE THREAD

**Issue by bysameng** [rngtm/Unity-AssetBookmarker#1]
Hi,

Thanks for such a wonderful asset. I really love it. The asset bookmarks work very well.
However I have run into a problem on Unity 2020.2.1f1 when trying to use Hierarchy bookmarks.

To Reproduce:

1. Install AssetBookmarker through Package Manager
2. Open Hierarchy Bookmarker window
3. Click "Apply" in Hierarchy Search filter. (Or, you can enter any text)
4. Error is thrown.

`AssetBookmarker.Hierarchy.SceneHierarchyAccessor.SetSearchFilter (System.String filter) (at Library/PackageCache/com.rngtm.asset-bookmarker@60b1ea313c/Editor/Hierarchy/Editor/Utility/SceneHierarchyAccessor.cs:32)
AssetBookmarker.Hierarchy.HierarchyBookmarkWindow+<>c__DisplayClass5_0.<CreateSearchInfoList>b__2 (UnityEngine.Rect rect, System.Int32 index, System.Boolean isActive, System.Boolean isFocused) (at Library/PackageCache/com.rngtm.asset-bookmarker@60b1ea313c/Editor/Hierarchy/Editor/GUI/HierarchyBookmarkWindow.cs:105)
UnityEditorInternal.ReorderableList.DoListElements (UnityEngine.Rect listRect, UnityEngine.Rect visibleRect) (at /Users/bokken/buildslave/unity/build/Editor/Mono/GUI/ReorderableList.cs:895)
UnityEditorInternal.ReorderableList.DoLayoutList () (at /Users/bokken/buildslave/unity/build/Editor/Mono/GUI/ReorderableList.cs:662)
AssetBookmarker.Hierarchy.HierarchyBookmarkWindow.OnGUI () (at Library/PackageCache/com.rngtm.asset-bookmarker@60b1ea313c/Editor/Hierarchy/Editor/GUI/HierarchyBookmarkWindow.cs:45)`

**Comment by bysameng** [comment]
I fixed the error. I attached a script file showing changes. I do not understand how to do pull requests, but I hope this helps.
[SceneHierarchyAccessor.cs.zip](https://github.com/rngtm/Unity-AssetBookmarker/files/5843947/SceneHierarchyAccessor.cs.zip)

**Comment by rngtm** [comment]
I've added support for Unity2020.2.
